### ISSUE TITLE
Throwing an exception inside map doesn't trigger retries

### ISSUE THREAD

**Issue by harrigan** [joegallo/robert-bruce#10]
``` clj
(try-try-again
  (fn []
    (map
      #(do
        (println "foobar:" %)
        (throw (Exception.)))
    (range 5))))
```

produces

```
foobar: 0
clojure.lang.Compiler$CompilerException: java.lang.Exception
```

with no retries. Should it? I'm likely missing something obvious here.

**Comment by joegallo** [comment]
Inside try-try-again, you're creating a lazy seq using map. No error is generated. You return that lazy-seq to the calling context of try-try-again, again with no error being generated.

Then, I'm assuming in your repl, you go to use or print the contents of your lazy seq, and finally the map is sortof actually evaluated, and you trigger the exception. But by now you're outside the context of try-try-again, and there's no opportunity for retries.

That is, you're being bitten by laziness. Use a doall to force the map to run inside try-try-again.
