### ISSUE TITLE
the docs for :decay are not clear

### ISSUE THREAD

**Issue by hiredman** [joegallo/robert-bruce#6]
the docs for :decay say that you can specify a function for decay, which will be passed the sleep value, but not if the function is then responsible for sleeping, or if the function should return a number.

looking at the source code it looks like it should return a number

**Comment by joegallo** [comment]
Ah, good point. I'll fix that.

**Comment by joegallo** [comment]
Hopefully 1e066e8c66efcf1250a04b2c121ad65eb3d9586b clears things up a bit. Thanks!
