### ISSUE TITLE
Documentation is inaccurate

### ISSUE THREAD

**Issue by smishmash** [joegallo/robert-bruce#9]
Released version 0.7.1 does not support :return? Both of these are referenced in README.

**Comment by joegallo** [comment]
You're reading the README of the master branch, which had changes in it that hadn't made it into a released version yet.

Anyway, 0.8.0 was released a few minutes ago, so upgrade to that and you'll be able to use `:return?`.

Thanks for the reminder about that, it was really just waiting on me to get around to it.

Cheers!
